branches:
  only:
    - master

git:
  lfs_skip_smudge: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

matrix:
  include:
    - language: node_js
      node_js:
        - 8.9.1
      sudo: false
      script:
        - npm run lint
    - language: objective-c
      os: osx
      osx_image: xcode9.3
      cache:
        yarn: true
        directories:
          - example/node_modules
          - $HOME/Library/Developer/Xcode/DerivedData
      before_script:
        - brew install git-lfs
        - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
        - git lfs pull
        - cd example
        - yarn
        - cd ios
      script:
        - xcodebuild -project EaseMob-Example.xcodeproj -scheme EaseMob-Example
          -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3' build
    - language: android
      android:
        components:
          - build-tools-27.0.1
          - android-27
      cache:
        yarn: true
        directories:
          - example/node_modules
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      before_script:
        - cd example
        - yarn
        - cd android
      script:
        - gradle build