branches:
  only:
    - master

matrix:
  include:
    - language: node_js
      node_js:
        - 8.9.1
      sudo: false
      script:
        - npm run lint
    - language: objective-c
      os: osx
      osx_image: xcode9.3
      cache:
        cocoapods: true
        yarn: true
        directories:
          - example/node_modules
          - $HOME/Library/Developer/Xcode/DerivedData
          - $HOME/.rncache
      before_script:
        - npm install -g yarn
        - cd example
        - yarn
        - cd ios
        - pod install --repo-update
      script:
        - xcodebuild -workspace EaseMob-Example.xcworkspace -scheme EaseMob-Example
          -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3' build
    - language: android
      android:
        components:
          - platform-tools
          - tools
          - build-tools-27.0.3
          - android-27
        licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
      cache:
        yarn: true
        directories:
          - example/node_modules
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      before_script:
        - nvm install 8
        - nvm use 8
        - npm install -g yarn
        - cd example
        - yarn
        - cd android
      script:
        - ./gradlew build